### ISSUE TITLE
Why not put as NPM module?

### ISSUE THREAD

**Issue by fuechter** [pinceladasdaweb/Node-CEP#1]
...

**Comment by pinceladasdaweb** [comment]
@alexandref93 

The code is still not good enough for that, but it's something to think about the future.

**Comment by fuechter** [comment]
okay.

2015-02-25 9:37 GMT-03:00 Pedro Rogério notifications@github.com:

> @alexandref93 https://github.com/alexandref93
> 
> The code is still not good enough for that, but it's something to think
> about the future.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/pinceladasdaweb/Node-CEP/issues/1#issuecomment-75952903
> .

## 

Carlos A. Fuechter
@alexandref93 http://twitter.com/#!/alexandref93
